import { expect, test } from '@playwright/test';
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

/*
 * scripts/replay-coverage-keep.mjs, run END TO END against a throwaway data/
 * corpus. It replays the coverage keep rule (citesBill, "The keep rule" in
 * scripts/coverage-query.mjs — the 2026-09-27 audit's SY-04) over the stored
 * coverage of every live Big Question vehicle and drops what fails it.
 *
 * What it pins:
 *   - only vehicles of NON-retired questions are judged; every other bill,
 *     and the "_" metadata keys, are written back untouched, in order;
 *   - a vehicle left with nothing leaves the file;
 *   - --dry-run writes nothing; a second run changes nothing;
 *   - the output is the same compact JSON the nightly sync writes;
 *   - it needs no key and makes no network call (the child gets a minimal env
 *     with no key in it, and a fetch that throws).
 */

const REPO = process.cwd();
const SCRIPT = join(REPO, 'scripts/replay-coverage-keep.mjs');

type Json = Record<string, unknown>;
const bill = (type: string, number: number, over: Json = {}) => ({
  bill_type: type,
  bill_number: number,
  congress_number: 119,
  title: `${type.toUpperCase()} ${number}`,
  press_names: null,
  news_query: null,
  ...over,
});

const BILLS = [
  bill('hconres', 89, { news_query: 'President "Iran hostilities"' }),
  bill('s', 4668, { press_names: ['Protect College Sports Act'] }),
  bill('hr', 7000, { press_names: ['Retired Question Act'] }),
  bill('hr', 101, { press_names: ['Ordinary Act'] }),
];
const a = (title: string, source: string, snippet: string | null = null) => ({
  title,
  url: `https://www.${source}/${title.replace(/\W+/g, '-')}`,
  source,
  snippet,
  publishedAt: '2026-09-20',
  rated: false,
});
const COVERAGE = {
  'hconres-89-119': [a('Indian Shares Seen Higher At Open', 'rttnews.com'), a('EU social media bans', 'thestockmarketwatch.com')],
  's-4668-119': [a('College sports act overcomes filibuster', 'washingtontimes.com'), a('Protect College Sports Act clears cloture', 'cbsnews.com')],
  'hr-7000-119': [a('Unrelated story', 'example.com')],
  'hr-101-119': [a('Also unrelated', 'example.com')],
  _checkedAt: { 'hconres-89-119': '2026-09-26', 's-4668-119': '2026-09-26' },
  _note: 'Generated by scripts/sync-coverage.mjs.',
};
const MOMENTS = {
  'iran-war-powers': { status: 'live', vehicles: [{ slug: 'hconres-89-119' }] },
  'paying-college-athletes': { status: 'live', vehicles: [{ slug: 's-4668-119' }] },
  'an-old-question': { status: 'retired', vehicles: [{ slug: 'hr-7000-119' }] },
};

// A preload that fails the run on ANY network call.
const NO_NETWORK = `data:text/javascript,${encodeURIComponent(
  "globalThis.fetch = async () => { throw new Error('replay-coverage-keep made a network call'); };",
)}`;

function runReplay(args: string[] = [], { coverage = COVERAGE as Json, runs = 1 } = {}) {
  const dir = mkdtempSync(join(tmpdir(), 'replay-coverage-keep-'));
  mkdirSync(join(dir, 'data'));
  const put = (name: string, value: unknown) => writeFileSync(join(dir, 'data', name), JSON.stringify(value));
  put('bills.json', BILLS);
  put('coverage.json', coverage);
  put('moments.json', MOMENTS);
  const outputs: string[] = [];
  const raws: string[] = [];
  let status: number | null = null;
  for (let i = 0; i < runs; i++) {
    const run = spawnSync(process.execPath, ['--import', NO_NETWORK, SCRIPT, ...args], {
      cwd: dir,
      encoding: 'utf8',
      timeout: 60_000,
      env: { PATH: process.env.PATH ?? '' } as unknown as NodeJS.ProcessEnv,
    });
    status = run.status;
    outputs.push(`${run.stdout}\n${run.stderr}`);
    raws.push(readFileSync(join(dir, 'data/coverage.json'), 'utf8'));
  }
  rmSync(dir, { recursive: true, force: true });
  return { status, outputs, raws, output: outputs.at(-1)!, raw: raws.at(-1)!, coverage: JSON.parse(raws.at(-1)!) };
}

test.describe('replay-coverage-keep.mjs end to end (no network, no key)', () => {
  test('drops what fails the keep rule on live vehicles only, and leaves everything else as it was', () => {
    const { status, output, coverage } = runReplay();
    expect(status, output).toBe(0);
    // Every H.Con.Res. 89 row named nothing: the vehicle leaves the file.
    expect(coverage['hconres-89-119']).toBeUndefined();
    // S. 4668 keeps the row that prints its name, drops the paraphrase.
    expect(coverage['s-4668-119'].map((x: Json) => x.title)).toEqual(['Protect College Sports Act clears cloture']);
    // A retired question's vehicle, and a bill that is no vehicle at all, are not judged.
    expect(coverage['hr-7000-119']).toEqual(COVERAGE['hr-7000-119']);
    expect(coverage['hr-101-119']).toEqual(COVERAGE['hr-101-119']);
    expect(coverage._checkedAt).toEqual(COVERAGE._checkedAt);
    expect(coverage._note).toBe(COVERAGE._note);
    expect(Object.keys(coverage)).toEqual(['s-4668-119', 'hr-7000-119', 'hr-101-119', '_checkedAt', '_note']);
    expect(output).toContain('hconres-89-119: 2 -> 0 stored');
    expect(output).toContain('s-4668-119: 2 -> 1 stored');
    expect(output).toContain('keep (name)  cbsnews.com [not rated] | Protect College Sports Act clears cloture');
    expect(output).toContain(
      'replay-coverage-keep: 3 stored article(s) dropped on 2 vehicle(s) (1 left with no coverage); data/coverage.json 4 -> 3 bills, 6 -> 3 articles',
    );
  });

  test('writes the same compact JSON the nightly writes', () => {
    const { raw, coverage } = runReplay();
    expect(raw).toBe(JSON.stringify(coverage));
    expect(raw.endsWith('\n')).toBe(false);
  });

  test('--dry-run prints the verdicts and writes nothing', () => {
    const { status, output, raw } = runReplay(['--dry-run']);
    expect(status, output).toBe(0);
    expect(output).toContain('(dry run — nothing written)');
    expect(output).toContain('hconres-89-119: 2 -> 0 stored');
    expect(raw).toBe(JSON.stringify(COVERAGE));
  });

  test('a second run changes nothing (idempotent), and a clean file is not rewritten', () => {
    const { raws, outputs } = runReplay([], { runs: 2 });
    expect(raws[1]).toBe(raws[0]);
    expect(outputs[1]).toContain('replay-coverage-keep: 0 stored article(s) dropped on 0 vehicle(s)');
  });
});
