'use client';

import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { useLocale, useTranslations } from 'next-intl';

/*
 * THE SCREENCAST WALKTHROUGH — "watch the whole thing", owner pick 2A
 * (2026-08-01, round 3). A video-shaped player whose frames are REAL
 * captures of the real product (public/walkthrough/{locale}/step-N.png,
 * regenerated by scripts described in the capture commit — never mockups,
 * never fiction), one frame per step of the same four-step route the list
 * beside it prints. It replaced two collapsed demo disclosures ("See how a
 * call works" and the phone transcript); the transcript's load-bearing
 * reassurance — nothing else happens, voicemail counts — survives as the
 * note under the player, reusing the same demoNoteLead/demoNote keys.
 *
 * HONESTY RULES BAKED IN:
 * - The header's duration claim must match the player: 4 scenes x 7s = 28s,
 *   stated as "about 30 seconds". Change SCENE_MS or the scene count and the
 *   `screencastDur` strings must change with them.
 * - Never autoplays. Play is a user decision (and reduced-motion visitors
 *   get the same paused start as everyone else); playback stops at the last
 *   frame rather than looping at the reader.
 * - Frames are bilingual: the ES page shows ES captures, so a Spanish
 *   reader is never walked through an English UI.
 *
 * A11y: the step markers are real buttons at the 44px floor, named "Step N
 * of 4: {title}"; the frame img is alt="" because the visible caption and
 * the marker names carry the same information (a picture of the UI the
 * caption already describes). Scene changes announce via the caption row's
 * aria-live="polite".
 */

const STEPS = [1, 2, 3, 4] as const;
const SCENE_MS = 7000;

export function HomeScreencast() {
  const t = useTranslations('home');
  const locale = useLocale();
  const [step, setStep] = useState(1);
  const [playing, setPlaying] = useState(false);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (!playing) return;
    timer.current = setInterval(() => {
      setStep((s) => {
        if (s >= STEPS.length) {
          setPlaying(false);
          return s;
        }
        return s + 1;
      });
    }, SCENE_MS);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [playing]);

  const stepTitle = t(`how${step}Title`);

  return (
    <div>
      <figure className="overflow-hidden rounded-control border-2 border-ink">
        <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1 bg-ink-deep px-4 py-2.5">
          <span className="text-2xs font-bold tracking-[0.08em] text-paper uppercase">
            {t('screencastTitle')}
          </span>
          <span className="text-2xs font-bold tracking-[0.08em] text-ink-pale uppercase">
            {t('screencastDur')}
          </span>
        </div>

        <div className="relative border-b-[1.5px] border-line-strong">
          <Image
            src={`/walkthrough/${locale}/step-${step}.png`}
            alt=""
            width={960}
            height={640}
            className="block w-full"
            sizes="(min-width: 48rem) 470px, 100vw"
            priority={false}
          />
          {/* The primary affordance whenever the player is not running. A
              rounded-control bar, never a circle — nothing in Oravan is a
              circle. Restarts from step 1 when the run has finished. */}
          {!playing && (
            <button
              type="button"
              onClick={() => {
                if (step >= STEPS.length) setStep(1);
                setPlaying(true);
              }}
              className="ring-gap absolute top-1/2 left-1/2 inline-flex min-h-12 -translate-x-1/2 -translate-y-1/2 items-center gap-2 rounded-control border-2 border-ink bg-paper px-6 py-3 font-bold text-ink hover:bg-tint"
            >
              <span aria-hidden>▶</span>
              {t('screencastPlay')}
            </button>
          )}
        </div>

        <figcaption className="flex flex-wrap items-center justify-between gap-x-4 gap-y-2 px-4 py-2">
          <span aria-live="polite" className="text-sm text-ink-2">
            <b className="font-extrabold text-ink tabular-nums">
              {t('screencastStep', { current: step, total: STEPS.length })}
            </b>{' '}
            — {stepTitle}
          </span>
          <span className="flex items-center">
            {playing && (
              <button
                type="button"
                onClick={() => setPlaying(false)}
                className="mr-1 inline-flex min-h-11 items-center px-2 text-xs font-bold tracking-[0.06em] text-ink-2 uppercase underline underline-offset-4 hover:text-ink"
              >
                {t('screencastPause')}
              </button>
            )}
            {STEPS.map((n) => (
              <button
                key={n}
                type="button"
                aria-label={t('screencastStepAria', {
                  n,
                  total: STEPS.length,
                  title: t(`how${n}Title`),
                })}
                aria-current={n === step ? 'step' : undefined}
                onClick={() => {
                  setPlaying(false);
                  setStep(n);
                }}
                className="group flex h-11 w-11 items-center justify-center"
              >
                {/* small stamped bar, not a dot — the 44px hit area is the
                    button around it */}
                <span
                  aria-hidden
                  className={`block h-1.5 w-6 rounded-stamp ${
                    n === step ? 'bg-ink' : 'bg-line group-hover:bg-line-strong'
                  }`}
                />
              </button>
            ))}
          </span>
        </figcaption>
      </figure>

      {/* The transcript's reassurance, kept: same keys it always had. */}
      <p className="mt-3 max-w-note text-sm text-pretty text-ink-2">
        <strong className="font-semibold text-ink">{t('demoNoteLead')}</strong> {t('demoNote')}
      </p>
    </div>
  );
}
