import en from '../messages/en.json';
import { formatCitation } from './format';
import { statusKeyFor, type StatusKeyBill } from './journey';
import { PRESIDENT_STYLE_RULE, presidentStyle } from './president-style.mjs';
import type { Bill, Stance, StatusLabelKey } from './types';

/*
 * The ONE call-script prompt builder (extracted from app/api/script/route.ts
 * for S21/F7 pregen): both the live route and scripts/pregen-scripts.mjs
 * import this, so the two paths can never drift into two different scripts
 * for the same (bill, stance, locale) - a pregenerated script must be
 * byte-for-byte what the route would have generated on demand.
 *
 * Deliberate behavior this preserves unchanged from the route's original
 * inline prompt: the model is always given the bill's ENGLISH ai_summary as
 * input content, in both locales - only `langLine` changes to ask for
 * Spanish output. The route never reads data/bills-es.json's decoded
 * overlay (lib/core's localizeBill) for this endpoint, so neither does
 * pregen; passing a locale-localized bill here would compute a different
 * content-version hash and a different prompt than the route ever has,
 * silently forking the two paths on day one.
 */

export const SCRIPT_MODEL = 'claude-sonnet-5-5';
export const SCRIPT_MAX_TOKENS = 520;
export const STANCES: Stance[] = ['support', 'oppose', 'undecided'];

/*
 * Prompt version — the cache-invalidation tag for the script GENERATION LOGIC.
 * lib/scriptcache.ts folds this into contentVersion(), so the content-version
 * key tracks the prompt as well as bill.ai_summary. BUMP THIS whenever you
 * change the prompt below or STANCE_LINES — otherwise the change never reaches
 * users: the cache keys on the summary alone, which a prompt edit doesn't
 * touch, so every visitor keeps being served the script generated by the OLD
 * prompt until the summary happens to change or the 24h TTL rolls. Bumping it
 * makes the next request a clean miss for EVERY (bill, stance, locale) and
 * regenerates against the current prompt (route + pregen alike).
 *   v1 (implicit) — original inline prompt
 *   v2 — S6 call-flow pass: chamber-neutral, time-neutral greeting,
 *        no-ambiguous-demonstrative, voicemail-safe close (2026-07-08)
 *
 * THE ONE DELIBERATE EXCEPTION (2026-09-29): PRESIDENT_STYLE_RULE was added to
 * the rules below WITHOUT a bump. The rule only changes how a script writes
 * "the president", finishScript restyles every new script anyway, and every
 * cached script expires inside 24 hours on its own — so a bump would buy at
 * most a day and pay for one extra generation of every script requested in
 * that day (bounded only by SCRIPT_DAY_MAX). Bills whose summary the same
 * change restyled get a new content version regardless, because the summary
 * is key material. Bumping to '3' is a one-line change if the owner wants
 * the old scripts gone at once.
 *
 * THE SECOND DELIBERATE EXCEPTION (2026-09-29): the `Current status:` line
 * below changed from the raw enum to the plain-words stage (scriptStage,
 * below) WITHOUT a bump, for the same reason. The cache TTL is 24 hours
 * (SCRIPT_TTL_SECONDS in lib/scriptcache.ts, written with the entry), so
 * every script written from the old line is gone within a day of the deploy,
 * and the nightly warmer (lib/pregen-runner.ts) skips a combo that is still
 * cached, so it does not re-spend on one either. A bump would buy at most
 * that day and pay for one extra generation of every script requested in it.
 */
export const PROMPT_VERSION = '2';

/**
 * The generated script as it is cached and served: trimmed, and restyled to
 * "the president" (docs/copy-style.md). The ONE finisher both the live route
 * (app/api/script/route.ts) and nightly pregen (lib/pregen-runner.ts) call, so
 * a pregenerated script stays byte-for-byte what the route would have made.
 */
export function finishScript(text: string, lang: 'en' | 'es'): string {
  return presidentStyle(text.trim(), lang);
}

const STANCE_LINES: Record<Stance, string> = {
  support: 'The caller SUPPORTS this bill and urges the member to vote for it.',
  oppose: 'The caller OPPOSES this bill and urges the member to vote against it.',
  undecided:
    "The caller is CONCERNED about this bill and has not settled on support or opposition. The script must register that concern and name the ONE thing that worries them (grounded in the summary). Close with a self-contained statement that asks the office to log the caller's concern and notes that the caller is watching for the office's position before deciding - phrased as a statement or a request-to-record, NEVER as a question aimed at the staffer (for example, never end on 'could you let me know where the member stands?'). The staffer only tallies positions; the closing line must be fully meaningful on its own, with no spoken reply or callback required, since it may be left on a voicemail.",
};

function langLine(lang: 'en' | 'es'): string {
  return lang === 'es'
    ? 'Write the script in natural, warm Latin American Spanish (tú form). Use the placeholders [TU NOMBRE] and [TU CIUDAD O CÓDIGO POSTAL].'
    : 'Write the script in plain, warm English at an 8th-grade reading level. Use the placeholders [YOUR NAME] and [YOUR TOWN OR ZIP].';
}

/*
 * THE STAGE THE SCRIPT WRITER IS TOLD (2026-09-29).
 *
 * The prompt used to say `Current status: ${bill.status}` — the stored enum,
 * verbatim. The stored status set has no value for a second chamber's passage
 * (BillStatus, lib/types.ts), so a measure both chambers have passed is still
 * stored as `passed_chamber`. On 2026-09-29 that was H.R. 4467 ("Passed Senate
 * without amendment by Unanimous Consent.") and ten more the site prints as
 * "Passed both chambers", plus H.Con.Res. 86, "Adopted by both chambers": the
 * script writer was handed "passed_chamber" for all twelve and never told the
 * second chamber had acted. The same line handed it `floor_vote` for a
 * calendar placement the record has been silent on for over 14 days, which
 * the site prints as "Placed on the calendar", and for a cloture or motion
 * text that is no placement at all ("Floor activity").
 *
 * It now gets the SAME stage the site prints: statusKeyFor(bill)
 * (lib/journey.ts), the status-label gate every surface that prints a status
 * label routes through (citizen site, embeds and MCP alike), so the script
 * and the page beside it cannot describe the bill two ways. The words are the
 * English label from messages/en.json `bills.status.*` — English in both
 * locales, because the rest of the model's input is English too (the module
 * note above); only langLine asks for Spanish output.
 *
 * The table is typed as Record<StatusLabelKey, string>, so a stage key that
 * messages/en.json does not label fails the typecheck rather than reaching a
 * prompt as `undefined`.
 */
const STAGE_LABELS: Record<StatusLabelKey, string> = en.bills.status;

/** The plain-words stage the prompt's `Current status:` line carries. */
export function scriptStage(bill: StatusKeyBill): string {
  return STAGE_LABELS[statusKeyFor(bill)];
}

export interface ScriptPromptInput {
  /**
   * Always the raw (English) bill - see the module note above. It carries the
   * record fields statusKeyFor reads (the last action, its date and the status
   * basis), not just `status`: the passage readings need them to tell "Passed
   * one chamber" from "Passed both chambers".
   */
  bill: Pick<Bill, 'bill_number' | 'short_title' | 'title' | 'ai_summary'> & StatusKeyBill;
  stance: Stance;
  lang: 'en' | 'es';
}

/** The exact 30-second call-script prompt, shared by the route and pregen. */
export function buildScriptPrompt({ bill, stance, lang }: ScriptPromptInput): string {
  const citation = formatCitation(bill.bill_type, bill.bill_number);

  return `Write a 30-second phone script for a constituent calling their members of Congress about this bill. The exact same script is read verbatim to the caller's U.S. Representative's office and, separately, to both of the caller's U.S. Senators' offices - so it must never assume, name, or imply a single chamber.

Bill: ${citation} — ${bill.short_title ?? bill.title}
Plain-language summary: ${bill.ai_summary ?? bill.title}
Current status: ${scriptStage(bill)}

${STANCE_LINES[stance]}

${langLine(lang)}

Rules:
- 60-90 words. It must be comfortably readable aloud in 30 seconds.
- Structure: greeting + name placeholder + constituent location placeholder, the bill by its number, the position, ONE concrete reason grounded in the summary, a clear ask, thanks.
- Greeting must be time-neutral: e.g. "Hello, my name is..." / "Hola, me llamo...". NEVER use a time-of-day greeting ("good morning," "good afternoon," "good evening," "buenos días," "buenas tardes," "buenas noches," or similar) - calls happen at any hour, including after business hours.
- Chamber-neutral, always: NEVER address or describe the recipient as "Representative," "Senator," "Congressman," "Congresswoman," or the Spanish equivalents ("representante," "senador," "senadora," "congresista") used as a title - the same script is read to a Representative's office and to Senators' offices alike. Refer to the recipient generically instead: "your office" / "the office" ("su oficina" / "la oficina"). Naming the bill and stating the position is fine; naming a chamber or title is not.
- No ambiguous "this" or "it": never use a bare "this" or "it" as a sentence's subject unless its antecedent is the noun immediately before it. Name what's being referred to instead - the bill by its short number, "this bill," or the position/concern by name - so no sentence can be misheard as meaning the opposite of what's intended.
- Refer to the bill exactly as "${citation}" - do not alter, translate, or extend that citation.
- Must work equally well read to a live staffer or left as a voicemail: the final sentence has to be a self-contained statement - never a question mark, and never a request whose meaning depends on a spoken reply or a callback.
- Strictly nonpartisan tone: no party language, no attacks, no alarmism, no advocacy-group jargon.
${PRESIDENT_STYLE_RULE}
- Do not invent facts beyond the summary provided.
- Plain text only: no markdown, no asterisks, no bullet points, no headers.
- Output ONLY the script text, no commentary.`;
}
