import { formatCitation } from './format';
import type { Bill, Stance } from './types';

/*
 * The ONE call-script prompt builder (extracted from app/api/script/route.ts
 * for S21/F7 pregen): both the live route and scripts/pregen-scripts.mjs
 * import this, so the two paths can never drift into two different scripts
 * for the same (bill, stance, locale) - a pregenerated script must be
 * byte-for-byte what the route would have generated on demand.
 *
 * Deliberate behavior this preserves unchanged from the route's original
 * inline prompt: the model is always given the bill's ENGLISH ai_summary as
 * input content, in both locales - only `langLine` changes to ask for
 * Spanish output. The route never reads data/bills-es.json's decoded
 * overlay (lib/core's localizeBill) for this endpoint, so neither does
 * pregen; passing a locale-localized bill here would compute a different
 * content-version hash and a different prompt than the route ever has,
 * silently forking the two paths on day one.
 */

export const SCRIPT_MODEL = 'claude-sonnet-5';
export const SCRIPT_MAX_TOKENS = 520;
export const STANCES: Stance[] = ['support', 'oppose', 'undecided'];

/*
 * Prompt version — the cache-invalidation tag for the script GENERATION LOGIC.
 * lib/scriptcache.ts folds this into contentVersion(), so the content-version
 * key tracks the prompt as well as bill.ai_summary. BUMP THIS whenever you
 * change the prompt below or STANCE_LINES — otherwise the change never reaches
 * users: the cache keys on the summary alone, which a prompt edit doesn't
 * touch, so every visitor keeps being served the script generated by the OLD
 * prompt until the summary happens to change or the 24h TTL rolls. Bumping it
 * makes the next request a clean miss for EVERY (bill, stance, locale) and
 * regenerates against the current prompt (route + pregen alike).
 *   v1 (implicit) — original inline prompt
 *   v2 — S6 call-flow pass: chamber-neutral, time-neutral greeting,
 *        no-ambiguous-demonstrative, voicemail-safe close (2026-07-08)
 */
export const PROMPT_VERSION = '2';

const STANCE_LINES: Record<Stance, string> = {
  support: 'The caller SUPPORTS this bill and urges the member to vote for it.',
  oppose: 'The caller OPPOSES this bill and urges the member to vote against it.',
  undecided:
    "The caller is CONCERNED about this bill and has not settled on support or opposition. The script must register that concern and name the ONE thing that worries them (grounded in the summary). Close with a self-contained statement that asks the office to log the caller's concern and notes that the caller is watching for the office's position before deciding - phrased as a statement or a request-to-record, NEVER as a question aimed at the staffer (for example, never end on 'could you let me know where the member stands?'). The staffer only tallies positions; the closing line must be fully meaningful on its own, with no spoken reply or callback required, since it may be left on a voicemail.",
};

function langLine(lang: 'en' | 'es'): string {
  return lang === 'es'
    ? 'Write the script in natural, warm Latin American Spanish (tú form). Use the placeholders [TU NOMBRE] and [TU CIUDAD O CÓDIGO POSTAL].'
    : 'Write the script in plain, warm English at an 8th-grade reading level. Use the placeholders [YOUR NAME] and [YOUR TOWN OR ZIP].';
}

export interface ScriptPromptInput {
  /** Always the raw (English) bill - see the module note above. */
  bill: Pick<Bill, 'bill_type' | 'bill_number' | 'short_title' | 'title' | 'ai_summary' | 'status'>;
  stance: Stance;
  lang: 'en' | 'es';
}

/** The exact 30-second call-script prompt, shared by the route and pregen. */
export function buildScriptPrompt({ bill, stance, lang }: ScriptPromptInput): string {
  const citation = formatCitation(bill.bill_type, bill.bill_number);

  return `Write a 30-second phone script for a constituent calling their members of Congress about this bill. The exact same script is read verbatim to the caller's U.S. Representative's office and, separately, to both of the caller's U.S. Senators' offices - so it must never assume, name, or imply a single chamber.

Bill: ${citation} — ${bill.short_title ?? bill.title}
Plain-language summary: ${bill.ai_summary ?? bill.title}
Current status: ${bill.status}

${STANCE_LINES[stance]}

${langLine(lang)}

Rules:
- 60-90 words. It must be comfortably readable aloud in 30 seconds.
- Structure: greeting + name placeholder + constituent location placeholder, the bill by its number, the position, ONE concrete reason grounded in the summary, a clear ask, thanks.
- Greeting must be time-neutral: e.g. "Hello, my name is..." / "Hola, me llamo...". NEVER use a time-of-day greeting ("good morning," "good afternoon," "good evening," "buenos días," "buenas tardes," "buenas noches," or similar) - calls happen at any hour, including after business hours.
- Chamber-neutral, always: NEVER address or describe the recipient as "Representative," "Senator," "Congressman," "Congresswoman," or the Spanish equivalents ("representante," "senador," "senadora," "congresista") used as a title - the same script is read to a Representative's office and to Senators' offices alike. Refer to the recipient generically instead: "your office" / "the office" ("su oficina" / "la oficina"). Naming the bill and stating the position is fine; naming a chamber or title is not.
- No ambiguous "this" or "it": never use a bare "this" or "it" as a sentence's subject unless its antecedent is the noun immediately before it. Name what's being referred to instead - the bill by its short number, "this bill," or the position/concern by name - so no sentence can be misheard as meaning the opposite of what's intended.
- Refer to the bill exactly as "${citation}" - do not alter, translate, or extend that citation.
- Must work equally well read to a live staffer or left as a voicemail: the final sentence has to be a self-contained statement - never a question mark, and never a request whose meaning depends on a spoken reply or a callback.
- Strictly nonpartisan tone: no party language, no attacks, no alarmism, no advocacy-group jargon.
- Do not invent facts beyond the summary provided.
- Plain text only: no markdown, no asterisks, no bullet points, no headers.
- Output ONLY the script text, no commentary.`;
}
