import en from '../messages/en.json';
import { formatCitation } from './format';
import { journeyEnding, passageState, statusKeyFor, type StatusKeyBill } from './journey';
import { PRESIDENT_STYLE_RULE, presidentStyle } from './president-style.mjs';
import type { Bill, Stance, StatusLabelKey } from './types';

/*
 * The ONE call-script prompt builder (extracted from app/api/script/route.ts
 * for S21/F7 pregen): both the live route and scripts/pregen-scripts.mjs
 * import this, so the two paths can never drift into two different scripts
 * for the same (bill, stance, locale) - a pregenerated script must be
 * byte-for-byte what the route would have generated on demand.
 *
 * Deliberate behavior this preserves unchanged from the route's original
 * inline prompt: the model is always given the bill's ENGLISH ai_summary as
 * input content, in both locales - only `langLine` changes to ask for
 * Spanish output. The route never reads data/bills-es.json's decoded
 * overlay (lib/core's localizeBill) for this endpoint, so neither does
 * pregen; passing a locale-localized bill here would compute a different
 * content-version hash and a different prompt than the route ever has,
 * silently forking the two paths on day one.
 */

export const SCRIPT_MODEL = 'claude-sonnet-5-5';
export const SCRIPT_MAX_TOKENS = 520;
export const STANCES: Stance[] = ['support', 'oppose', 'undecided'];

/*
 * Prompt version — the cache-invalidation tag for the script GENERATION LOGIC.
 * lib/scriptcache.ts folds this into contentVersion(), so the content-version
 * key tracks the prompt as well as bill.ai_summary. BUMP THIS whenever you
 * change the prompt below, STANCE_LINES, concernedLine or the passed-both
 * lines (PASSED_BOTH_WHERE, PASSED_BOTH_NEVER, passedBothStanceLine) —
 * otherwise the change never reaches users: the cache keys on the summary
 * alone, which a prompt edit doesn't touch, so every visitor keeps being
 * served the script generated by the OLD prompt until the summary happens to
 * change or the 24h TTL rolls. Bumping it makes the next request a clean miss
 * for EVERY (bill, stance, locale) and regenerates against the current prompt
 * (route + pregen alike).
 *   v1 (implicit) — original inline prompt
 *   v2 — S6 call-flow pass: chamber-neutral, time-neutral greeting,
 *        no-ambiguous-demonstrative, voicemail-safe close (2026-07-08)
 *   v3 — a bill both chambers have passed: the stance line asks the member
 *        for a public stand, never a vote that already happened, and says
 *        where the bill stands (passedBothReading, below; owner's pick 7 (a),
 *        2026-09-29). Bumped on the owner's pick, which named the cost: every
 *        cached script is rewritten as people ask for it, inside the existing
 *        SCRIPT_DAY_MAX (app/api/script/route.ts). The same bump also carries
 *        the two unbumped changes described below into every cached script at
 *        once, so their one-day wait is over too.
 *
 * THE ONE DELIBERATE EXCEPTION (2026-09-29): PRESIDENT_STYLE_RULE was added to
 * the rules below WITHOUT a bump. The rule only changes how a script writes
 * "the president", finishScript restyles every new script anyway, and every
 * cached script expires inside 24 hours on its own — so a bump would buy at
 * most a day and pay for one extra generation of every script requested in
 * that day (bounded only by SCRIPT_DAY_MAX). Bills whose summary the same
 * change restyled get a new content version regardless, because the summary
 * is key material. The v3 bump above, made later the same day for a
 * different change, retired those old scripts at once anyway.
 *
 * THE SECOND DELIBERATE EXCEPTION (2026-09-29): the `Current status:` line
 * below changed from the raw enum to the plain-words stage (scriptStage,
 * below) WITHOUT a bump, for the same reason. The cache TTL is 24 hours
 * (SCRIPT_TTL_SECONDS in lib/scriptcache.ts, written with the entry), so
 * every script written from the old line is gone within a day of the deploy,
 * and the nightly warmer (lib/pregen-runner.ts) skips a combo that is still
 * cached, so it does not re-spend on one either. A bump would buy at most
 * that day and pay for one extra generation of every script requested in it.
 */
export const PROMPT_VERSION = '3';

/**
 * The generated script as it is cached and served: trimmed, and restyled to
 * "the president" (docs/copy-style.md). The ONE finisher both the live route
 * (app/api/script/route.ts) and nightly pregen (lib/pregen-runner.ts) call, so
 * a pregenerated script stays byte-for-byte what the route would have made.
 */
export function finishScript(text: string, lang: 'en' | 'es'): string {
  return presidentStyle(text.trim(), lang);
}

/*
 * The concerned stance's closing instruction, shared by every stage so the
 * voicemail-safe wording cannot drift between them. `close` is the one clause
 * that differs: what the closing statement asks for besides logging the
 * concern.
 */
function concernedLine(close: string): string {
  return `The caller is CONCERNED about this bill and has not settled on support or opposition. The script must register that concern and name the ONE thing that worries them (grounded in the summary). Close with a self-contained statement that asks the office to log the caller's concern and ${close} - phrased as a statement or a request-to-record, NEVER as a question aimed at the staffer (for example, never end on 'could you let me know where the member stands?'). The staffer only tallies positions; the closing line must be fully meaningful on its own, with no spoken reply or callback required, since it may be left on a voicemail.`;
}

/** Every stage but a passage by both chambers (see passedBothReading). */
const STANCE_LINES: Record<Stance, string> = {
  support: 'The caller SUPPORTS this bill and urges the member to vote for it.',
  oppose: 'The caller OPPOSES this bill and urges the member to vote against it.',
  undecided: concernedLine("notes that the caller is watching for the office's position before deciding"),
};

/*
 * THE ASK WHEN BOTH CHAMBERS HAVE PASSED IT (owner's pick 7 (a), 2026-09-29).
 *
 * The report the owner answered: "Eleven bills have passed both chambers and
 * now wait on the president. Their call script still has a supporter ask the
 * member to 'vote for it', but the member already did." His pick: "for those
 * bills, the script asks the member to publicly back or oppose it before the
 * president acts, and says where it stands." So for these bills the stance
 * line asks for a PUBLIC STAND and never a vote. It never says how the member
 * voted, or whether they did: a unanimous-consent or voice-vote passage records
 * no member's vote, and the script is read to three offices whose records
 * differ.
 *
 * TWO READINGS, NOT ONE, because the site prints two different sentences
 * under the one "Passed both chambers" label (statusKeyFor's `passed_both`,
 * lib/journey.ts), and the script may not say more than the page beside it:
 *
 *   to_president   passageState stage 'both' on a vehicle whose path ends at
 *                  the president (journeyEnding): the second chamber passed
 *                  it without amendment, so both passed the same text. The
 *                  stepper says "It goes to the president next"
 *                  (`nowPassedBoth`, not clocked: that is Article I, Section
 *                  7's presentment requirement, not a forecast). The script
 *                  says so and asks for the stand before the president acts.
 *                  H.R. 4467 and six more House bills on 2026-09-29.
 *   next_unstated  everything else under that label. Mostly passageState
 *                  stage 'second': both chambers passed it and the record
 *                  does not say whether the two versions match
 *                  (`nowPassedSecond`), so it may go back to a chamber rather
 *                  than to the president. A concurrent resolution is always
 *                  this reading when it is not already `adopted`, and it never
 *                  goes to the president at all. Four Senate bills and
 *                  S.Con.Res. 29 on 2026-09-29. The script asks for the same
 *                  public stand, says both chambers have passed it, and names
 *                  no next step.
 *
 * Page 1 rule 6 is why the second reading exists: the report's premise ("now
 * wait on the president") holds for the first reading only, and a script
 * telling the office that S.Con.Res. 29 goes to the president would be false.
 *
 * ONE PLACE THIS IS STRICTER THAN THE STEPPER, stated rather than hidden: a
 * proposed constitutional amendment (journeyEnding 'states') at stage 'both'
 * would get `nowPassedBoth`, "It goes to the president next", on the page,
 * although it goes to the states. The script reads journeyEnding and gives it
 * `next_unstated`. The corpus held no such record on 2026-09-29.
 *
 * Returns null for every other stage, whose stance lines are unchanged.
 *
 * NOT KEY MATERIAL, like the stage line (lib/scriptcache.ts, "THE STAGE LINE
 * READS MORE THAN THIS KEY HOLDS"): a move between readings that leaves the
 * status and the last-action date alone lives at most one cache TTL.
 */
export type PassedBothReading = 'to_president' | 'next_unstated';

export type StanceLineBill = StatusKeyBill & Pick<Bill, 'title'>;

export function passedBothReading(bill: StanceLineBill): PassedBothReading | null {
  if (statusKeyFor(bill) !== 'passed_both') return null;
  const toPresident = passageState(bill).stage === 'both' && journeyEnding(bill.bill_type, bill.title) === 'president';
  return toPresident ? 'to_president' : 'next_unstated';
}

/** Where the bill stands, as the script must say it. */
const PASSED_BOTH_WHERE: Record<PassedBothReading, string> = {
  to_president:
    'Where the bill stands: both chambers of Congress have passed this bill, and it goes to the president next. The script must say so plainly.',
  next_unstated:
    'Where the bill stands: both chambers of Congress have passed this bill. The script must say so plainly, and must not say what happens to the bill next (for example, never say that it goes to the president).',
};

const PASSED_BOTH_NEVER =
  'NEVER ask the member to vote for or against this bill, and NEVER say or imply how the member voted, or whether the member voted at all.';

/**
 * The three stance lines for a bill both chambers have passed. Built from one
 * template so the three stay symmetric: support and oppose differ only in the
 * verb, and the concerned line asks for a public position without leaning
 * either way.
 */
function passedBothStanceLine(stance: Stance, reading: PassedBothReading): string {
  const before = reading === 'to_president' ? ' before the president acts on it' : '';
  const ask: Record<Stance, string> = {
    support: `The caller SUPPORTS this bill and urges the member to publicly back it${before}.`,
    oppose: `The caller OPPOSES this bill and urges the member to publicly oppose it${before}.`,
    undecided: concernedLine(`asks the member to state a public position on the bill${before}`),
  };
  return `${ask[stance]} ${PASSED_BOTH_WHERE[reading]} ${PASSED_BOTH_NEVER}`;
}

/** The stance line the prompt carries for this bill at its current stage. */
export function stanceLine(bill: StanceLineBill, stance: Stance): string {
  const reading = passedBothReading(bill);
  return reading ? passedBothStanceLine(stance, reading) : STANCE_LINES[stance];
}

function langLine(lang: 'en' | 'es'): string {
  return lang === 'es'
    ? 'Write the script in natural, warm Latin American Spanish (tú form). Use the placeholders [TU NOMBRE] and [TU CIUDAD O CÓDIGO POSTAL].'
    : 'Write the script in plain, warm English at an 8th-grade reading level. Use the placeholders [YOUR NAME] and [YOUR TOWN OR ZIP].';
}

/*
 * THE STAGE THE SCRIPT WRITER IS TOLD (2026-09-29).
 *
 * The prompt used to say `Current status: ${bill.status}` — the stored enum,
 * verbatim. The stored status set has no value for a second chamber's passage
 * (BillStatus, lib/types.ts), so a measure both chambers have passed is still
 * stored as `passed_chamber`. On 2026-09-29 that was H.R. 4467 ("Passed Senate
 * without amendment by Unanimous Consent.") and ten more the site prints as
 * "Passed both chambers", plus H.Con.Res. 86, "Adopted by both chambers": the
 * script writer was handed "passed_chamber" for all twelve and never told the
 * second chamber had acted. The same line handed it `floor_vote` for a
 * calendar placement the record has been silent on for over 14 days, which
 * the site prints as "Placed on the calendar", and for a cloture or motion
 * text that is no placement at all ("Floor activity").
 *
 * It now gets the SAME stage the site prints: statusKeyFor(bill)
 * (lib/journey.ts), the status-label gate every surface that prints a status
 * label routes through (citizen site, embeds and MCP alike), so the script
 * and the page beside it cannot describe the bill two ways. The words are the
 * English label from messages/en.json `bills.status.*` — English in both
 * locales, because the rest of the model's input is English too (the module
 * note above); only langLine asks for Spanish output.
 *
 * The table is typed as Record<StatusLabelKey, string>, so a stage key that
 * messages/en.json does not label fails the typecheck rather than reaching a
 * prompt as `undefined`.
 */
const STAGE_LABELS: Record<StatusLabelKey, string> = en.bills.status;

/** The plain-words stage the prompt's `Current status:` line carries. */
export function scriptStage(bill: StatusKeyBill): string {
  return STAGE_LABELS[statusKeyFor(bill)];
}

export interface ScriptPromptInput {
  /**
   * Always the raw (English) bill - see the module note above. It carries the
   * record fields statusKeyFor reads (the last action, its date and the status
   * basis), not just `status`: the passage readings need them to tell "Passed
   * one chamber" from "Passed both chambers".
   */
  bill: Pick<Bill, 'bill_number' | 'short_title' | 'title' | 'ai_summary'> & StatusKeyBill;
  stance: Stance;
  lang: 'en' | 'es';
}

/** The exact 30-second call-script prompt, shared by the route and pregen. */
export function buildScriptPrompt({ bill, stance, lang }: ScriptPromptInput): string {
  const citation = formatCitation(bill.bill_type, bill.bill_number);

  return `Write a 30-second phone script for a constituent calling their members of Congress about this bill. The exact same script is read verbatim to the caller's U.S. Representative's office and, separately, to both of the caller's U.S. Senators' offices - so it must never assume, name, or imply a single chamber.

Bill: ${citation} — ${bill.short_title ?? bill.title}
Plain-language summary: ${bill.ai_summary ?? bill.title}
Current status: ${scriptStage(bill)}

${stanceLine(bill, stance)}

${langLine(lang)}

Rules:
- 60-90 words. It must be comfortably readable aloud in 30 seconds.
- Structure: greeting + name placeholder + constituent location placeholder, the bill by its number, the position, ONE concrete reason grounded in the summary, a clear ask, thanks.
- Greeting must be time-neutral: e.g. "Hello, my name is..." / "Hola, me llamo...". NEVER use a time-of-day greeting ("good morning," "good afternoon," "good evening," "buenos días," "buenas tardes," "buenas noches," or similar) - calls happen at any hour, including after business hours.
- Chamber-neutral, always: NEVER address or describe the recipient as "Representative," "Senator," "Congressman," "Congresswoman," or the Spanish equivalents ("representante," "senador," "senadora," "congresista") used as a title - the same script is read to a Representative's office and to Senators' offices alike. Refer to the recipient generically instead: "your office" / "the office" ("su oficina" / "la oficina"). Naming the bill and stating the position is fine; naming a chamber or title is not.
- No ambiguous "this" or "it": never use a bare "this" or "it" as a sentence's subject unless its antecedent is the noun immediately before it. Name what's being referred to instead - the bill by its short number, "this bill," or the position/concern by name - so no sentence can be misheard as meaning the opposite of what's intended.
- Refer to the bill exactly as "${citation}" - do not alter, translate, or extend that citation.
- Must work equally well read to a live staffer or left as a voicemail: the final sentence has to be a self-contained statement - never a question mark, and never a request whose meaning depends on a spoken reply or a callback.
- Strictly nonpartisan tone: no party language, no attacks, no alarmism, no advocacy-group jargon.
${PRESIDENT_STYLE_RULE}
- Do not invent facts beyond the summary provided.
- Plain text only: no markdown, no asterisks, no bullet points, no headers.
- Output ONLY the script text, no commentary.`;
}
